FROM ubuntu:18.04
Maintainer The BitcoinHD Core developers <master@btchd.org>

# Dependency
RUN apt-get update && apt-get install build-essential libtool autotools-dev pkg-config make automake cmake curl python3 patch git -y
RUN apt-get install librsvg2-bin libtiff-tools bsdmainutils imagemagick libcap-dev libz-dev libbz2-dev python3-setuptools -y

# Build env
ENV BUILD_HOST='x86_64-apple-darwin14'
ENV BUILD_ARGS='--prefix=/ --enable-reduce-exports'
ENV BUILD_THREADS=1

# Workspace
VOLUME /workspace
WORKDIR /workspace

# Entrypoint
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT ["/bin/sh", "/usr/local/bin/docker-entrypoint.sh"]
