FROM ubuntu:18.04
Maintainer The BitcoinHD Core developers <master@btchd.org>

# Dependency
RUN sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list \
  && sed -i 's/security.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list \
  && apt-get update \
  && apt-get install build-essential libtool autotools-dev pkg-config make automake cmake curl python3 patch git -y
RUN apt-get install librsvg2-bin libtiff-tools bsdmainutils imagemagick libcap-dev libz-dev libbz2-dev python3-setuptools -y

# Build env
ENV BUILD_HOST='x86_64-apple-darwin14'
ENV BUILD_ARGS='--prefix=/ --enable-reduce-exports'
ENV BUILD_THREADS=1

# Workspace
RUN mkdir -p /workspace
Volume /workspace
WorkDir /workspace

# Entrypoint
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
